# Generated by Django 5.2.3 on 2025-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='inbound_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate in USD, e.g., 0.10 for 10 cents', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='outbound_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate in USD, e.g., 0.10 for 10 cents', max_digits=5, null=True),
        ),
    ]
