# Generated by Django 5.2.3 on 2025-06-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
        ('core', '0002_ghlauthcredentials_inbound_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='category_app.category'),
        ),
    ]
