# Generated by Django 5.2.3 on 2025-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ghlauthcredentials_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='is_contact_pulled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='is_conversation_pulled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
