# Generated by Django 5.2.3 on 2025-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ghlauthcredentials_is_contact_pulled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
