# Generated by Django 5.2.3 on 2025-06-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ghlauthcredentials_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='segment_length',
            field=models.IntegerField(blank=True, default=160, null=True),
        ),
    ]
