# Generated by Django 5.2.3 on 2025-06-13 13:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ghlauthcredentials_segment_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSDefaultConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_inbound_rate', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Default inbound rate in USD, e.g., 0.10 for 10 cents', max_digits=5)),
                ('default_outbound_rate', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Default outbound rate in USD, e.g., 0.10 for 10 cents', max_digits=5)),
                ('default_currency', models.CharField(default='USD', help_text='Default currency code, e.g., USD, EUR, GBP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Default Configuration',
                'verbose_name_plural': 'SMS Default Configuration',
            },
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
