# Generated by Django 5.2.3 on 2025-07-01 15:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_smsdefaultconfiguration_ghlauthcredentials_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='inbound_call_rate',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Rate in USD, e.g., 0.10 for 10 cents', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='is_calls_pulled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='outbound_call_rate',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Rate in USD, e.g., 0.10 for 10 cents', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='inbound_rate',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Rate in USD, e.g., 0.10 for 10 cents', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='outbound_rate',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Rate in USD, e.g., 0.10 for 10 cents', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smsdefaultconfiguration',
            name='default_inbound_rate',
            field=models.DecimalField(decimal_places=7, default=Decimal('0.10'), help_text='Default inbound rate in USD, e.g., 0.10 for 10 cents', max_digits=10),
        ),
        migrations.AlterField(
            model_name='smsdefaultconfiguration',
            name='default_outbound_rate',
            field=models.DecimalField(decimal_places=7, default=Decimal('0.10'), help_text='Default outbound rate in USD, e.g., 0.10 for 10 cents', max_digits=10),
        ),
    ]
