# Generated by Django 5.2.3 on 2025-07-01 16:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ghlauthcredentials_inbound_call_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsdefaultconfiguration',
            name='default_call_inbound_rate',
            field=models.DecimalField(decimal_places=7, default=Decimal('0.10'), help_text='Default inbound rate in USD, e.g., 0.10 for 10 cents', max_digits=10),
        ),
        migrations.AddField(
            model_name='smsdefaultconfiguration',
            name='default_call_outbound_rate',
            field=models.DecimalField(decimal_places=7, default=Decimal('0.10'), help_text='Default outbound rate in USD, e.g., 0.10 for 10 cents', max_digits=10),
        ),
    ]
