# Generated by Django 5.2.3 on 2025-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_smsdefaultconfiguration_default_call_inbound_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='call_price_ratio',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Rate in USD, e.g., 0.10 for 10 cents', max_digits=10, null=True),
        ),
    ]
