# Generated by Django 5.2.3 on 2025-07-03 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ghlauthcredentials_call_price_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauthcredentials',
            name='ghl_initial_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('call_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('call_status', models.CharField(blank=True, max_length=50, null=True)),
                ('called', models.CharField(blank=True, max_length=20, null=True)),
                ('called_city', models.CharField(blank=True, max_length=100, null=True)),
                ('called_country', models.CharField(blank=True, max_length=100, null=True)),
                ('called_state', models.CharField(blank=True, max_length=100, null=True)),
                ('called_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('caller', models.CharField(blank=True, max_length=20, null=True)),
                ('caller_city', models.CharField(blank=True, max_length=100, null=True)),
                ('caller_country', models.CharField(blank=True, max_length=100, null=True)),
                ('caller_state', models.CharField(blank=True, max_length=100, null=True)),
                ('caller_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('from_city', models.CharField(blank=True, max_length=100, null=True)),
                ('from_country', models.CharField(blank=True, max_length=100, null=True)),
                ('from_state', models.CharField(blank=True, max_length=100, null=True)),
                ('from_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('to_number', models.CharField(blank=True, max_length=20, null=True)),
                ('to_city', models.CharField(blank=True, max_length=100, null=True)),
                ('to_country', models.CharField(blank=True, max_length=100, null=True)),
                ('to_state', models.CharField(blank=True, max_length=100, null=True)),
                ('to_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('first_time', models.BooleanField(blank=True, default=False, null=True)),
                ('recording_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ghl_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_reports', to='core.ghlauthcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='FirebaseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('token_type', models.CharField(max_length=50)),
                ('refresh_token', models.TextField()),
                ('id_token', models.TextField()),
                ('user_id', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ghl_credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_token', to='core.ghlauthcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityToolkitAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
                ('id_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_in', models.IntegerField()),
                ('is_new_user', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ghl_credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identitytoolkit_auth', to='core.ghlauthcredentials')),
            ],
        ),
        migrations.CreateModel(
            name='LeadConnectorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('trace_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ghl_credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leadconnector_auth', to='core.ghlauthcredentials')),
            ],
        ),
    ]
