# Generated by Django 5.2.3 on 2025-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ghlauthcredentials_ghl_initial_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
