# Generated by Django 5.2.3 on 2025-07-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_callreport_conversation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callreport',
            name='called',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='called_city',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='called_country',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='called_state',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='called_zip',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='caller',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='caller_city',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='caller_country',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='caller_state',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='caller_zip',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='from_country',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='from_zip',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='to_country',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='to_state',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='to_zip',
        ),
    ]
