# Generated by Django 5.2.3 on 2025-07-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0008_alter_callrecord_duration_alter_callrecord_status'),
        ('core', '0013_remove_callreport_called_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callreport',
            name='ghl_credential',
        ),
        migrations.AddField(
            model_name='callreport',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_report', to='accounts_management_app.ghlconversation'),
        ),
    ]
