# Generated by Django 5.2.3 on 2025-07-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_callreport_ghl_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callreport',
            name='ghl_credential',
        ),
    ]
