# Generated by Django 5.2.3 on 2025-07-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_callreport_ghl_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='ghl_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_reports', to='core.ghlauthcredentials'),
        ),
    ]
