# Generated by Django 5.2.3 on 2025-09-02 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_locationsynclog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationsynclog',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='locationsynclog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationsynclog',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='locationsynclog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fetching_contacts', 'Fetching Contacts'), ('fetching_conversations', 'Fetching Conversations'), ('fetching_calls', 'Fetching Calls'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
