# Generated by Django 5.2.3 on 2025-09-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0014_textmessage_text_messag_directi_666a94_idx'),
        ('category_app', '0001_initial'),
        ('core', '0019_alter_locationsynclog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callreport',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['conversation', 'date_added'], name='core_callre_convers_045c69_idx'),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['duration', 'date_added'], name='core_callre_duratio_276df3_idx'),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['direction', 'date_added'], name='core_callre_directi_0f6b07_idx'),
        ),
        migrations.AddIndex(
            model_name='ghlauthcredentials',
            index=models.Index(fields=['is_approved', 'company_id', 'category_id'], name='core_ghlaut_is_appr_6b6215_idx'),
        ),
        migrations.AddIndex(
            model_name='ghlauthcredentials',
            index=models.Index(fields=['company_id', 'category_id'], name='core_ghlaut_company_cb7f62_idx'),
        ),
    ]
