# Generated by Django 5.2.3 on 2025-09-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
        ('core', '0021_alter_ghlauthcredentials_ghl_initial_refresh_token'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ghlauthcredentials',
            name='core_ghlaut_is_appr_6b6215_idx',
        ),
        migrations.RemoveIndex(
            model_name='ghlauthcredentials',
            name='core_ghlaut_company_cb7f62_idx',
        ),
        migrations.AddIndex(
            model_name='ghlauthcredentials',
            index=models.Index(fields=['location_id', 'is_approved'], name='core_ghlaut_locatio_faaa49_idx'),
        ),
        migrations.AddIndex(
            model_name='ghlauthcredentials',
            index=models.Index(fields=['company_id', 'is_approved'], name='core_ghlaut_company_2b7785_idx'),
        ),
        migrations.AddIndex(
            model_name='ghlauthcredentials',
            index=models.Index(fields=['category_id', 'is_approved'], name='core_ghlaut_categor_a9cc56_idx'),
        ),
    ]
