# Generated by Django 5.2.3 on 2025-09-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0016_analyticscachelog_delete_analyticscachejob_and_more'),
        ('core', '0022_remove_ghlauthcredentials_core_ghlaut_is_appr_6b6215_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='callreport',
            name='core_callre_convers_045c69_idx',
        ),
        migrations.RemoveIndex(
            model_name='callreport',
            name='core_callre_duratio_276df3_idx',
        ),
        migrations.RemoveIndex(
            model_name='callreport',
            name='core_callre_directi_0f6b07_idx',
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['date_added', 'direction'], name='core_callre_date_ad_6b0543_idx'),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['location_id', 'date_added'], name='core_callre_locatio_814083_idx'),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['ghl_credential', 'date_added'], name='core_callre_ghl_cre_59fd14_idx'),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['direction'], name='core_callre_directi_5a6524_idx'),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['location_id'], name='core_callre_locatio_912008_idx'),
        ),
    ]
