# Generated by Django 5.2.3 on 2025-09-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_callreport_core_callre_convers_045c69_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='company_name',
            field=models.CharField(default='Pawn Leads', max_length=255),
        ),
    ]
