# Generated by Django 5.2.3 on 2025-09-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_ghlauthcredentials_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('balance', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.CharField(blank=True, max_length=50, null=True)),
                ('total_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('message_date', models.DateTimeField(blank=True, null=True)),
                ('prev_wallet_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_wallet_credits', models.CharField(blank=True, max_length=50, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ghl_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.ghlauthcredentials')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='core_ghltra_date_2a4b6a_idx'), models.Index(fields=['ghl_credential', 'date'], name='core_ghltra_ghl_cre_4cef87_idx'), models.Index(fields=['location_name', 'date'], name='core_ghltra_locatio_b2d4ff_idx')],
            },
        ),
    ]
