# Generated by Django 5.2.3 on 2025-09-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ghltransaction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ghltransaction',
            name='core_ghltra_date_2a4b6a_idx',
        ),
        migrations.AddField(
            model_name='ghltransaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ghltransaction',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ghltransaction',
            name='message_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='ghltransaction',
            index=models.Index(fields=['transaction_type'], name='core_ghltra_transac_4dcfa8_idx'),
        ),
    ]
