# Generated by Django 5.2.3 on 2025-09-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_ghltransaction_core_ghltra_date_2a4b6a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghltransaction',
            name='parsed_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationsynclog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fetching_contacts', 'Fetching Contacts'), ('fetching_conversations', 'Fetching Conversations'), ('fetching_calls', 'Fetching Calls'), ('fetching_transactions', 'Fetching Transactions'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
