# Generated by Django 5.2.3 on 2025-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_ghltransaction_parsed_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ghltransaction',
            name='core_ghltra_ghl_cre_4cef87_idx',
        ),
        migrations.RemoveIndex(
            model_name='ghltransaction',
            name='core_ghltra_locatio_b2d4ff_idx',
        ),
        migrations.AddIndex(
            model_name='ghltransaction',
            index=models.Index(fields=['parsed_date', 'transaction_type', 'ghl_credential'], name='core_ghltra_parsed__67d6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='ghltransaction',
            index=models.Index(fields=['ghl_credential'], name='core_ghltra_ghl_cre_979359_idx'),
        ),
        migrations.AddIndex(
            model_name='ghltransaction',
            index=models.Index(fields=['parsed_date'], name='core_ghltra_parsed__ec792a_idx'),
        ),
    ]
