# Generated by Django 5.2.3 on 2025-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_ghltransaction_core_ghltra_ghl_cre_4cef87_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghltransaction',
            name='total_segments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
