# Generated by Django 5.2.3 on 2025-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_ghltransaction_total_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsynclog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fetching_contacts', 'Fetching Contacts'), ('fetching_conversations', 'Fetching Conversations'), ('fetching_calls', 'Fetching Calls'), ('fetching_transactions', 'Fetching Transactions'), ('success', 'Success'), ('fetching_segments', 'Fetching Segments'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
