# Generated by Django 5.2.3 on 2025-09-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_locationsynclog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghlauthcredentials',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
