# Generated by Django 5.2.3 on 2025-06-11 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_ghlauthcredentials_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dnd', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=list)),
                ('location_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GHLConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100, unique=True)),
                ('last_message_body', models.TextField(blank=True, null=True)),
                ('last_message_type', models.CharField(blank=True, max_length=50, null=True)),
                ('last_message_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('last_outbound_action', models.CharField(blank=True, max_length=50, null=True)),
                ('unread_count', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('last_manual_message_date', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('contact', models.ForeignKey(blank=True, db_column='contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_management_app.contact', to_field='contact_id')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.ghlauthcredentials')),
            ],
            options={
                'db_table': 'ghl_conversation',
            },
        ),
    ]
