# Generated by Django 5.2.3 on 2025-06-11 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(default='text/plain', max_length=100)),
                ('message_type', models.CharField(choices=[('TYPE_SMS', 'SMS'), ('TYPE_EMAIL', 'Email'), ('TYPE_CALL', 'Call'), ('TYPE_VOICEMAIL', 'Voicemail'), ('TYPE_FACEBOOK', 'Facebook'), ('TYPE_GOOGLE_REVIEW', 'Google Review'), ('TYPE_WEBCHAT', 'Web Chat')], max_length=50)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], max_length=20, null=True)),
                ('type', models.IntegerField(help_text='Message type ID from API')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts_management_app.ghlconversation')),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['conversation', 'date_added'], name='accounts_ma_convers_cf0d31_idx')],
            },
        ),
    ]
