# Generated by Django 5.2.3 on 2025-06-11 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0002_ghlmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ghlmessage',
            new_name='ghl_message_convers_b9767e_idx',
            old_name='accounts_ma_convers_cf0d31_idx',
        ),
        migrations.AlterModelTable(
            name='ghlmessage',
            table='ghl_message',
        ),
    ]
