# Generated by Django 5.2.3 on 2025-06-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0004_textmessage_delete_ghlmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='body_length',
            field=models.IntegerField(default=0, help_text='Length of the message body'),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='segments',
            field=models.IntegerField(default=1, help_text='Number of SMS segments used'),
        ),
        migrations.AddIndex(
            model_name='textmessage',
            index=models.Index(fields=['segments', 'date_added'], name='text_messag_segment_33cbfa_idx'),
        ),
    ]
