# Generated by Django 5.2.3 on 2025-06-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0005_textmessage_body_length_textmessage_segments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('webhook_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
