# Generated by Django 5.2.3 on 2025-07-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0006_webhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('alt_id', models.CharField(blank=True, help_text='Alternative ID from GHL', max_length=255, null=True)),
                ('message_type', models.CharField(default='TYPE_CALL', max_length=50)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('no-answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('type', models.IntegerField(help_text='Message type ID from API')),
                ('duration', models.IntegerField(default=0, help_text='Call duration in seconds')),
                ('duration_formatted', models.CharField(blank=True, help_text='Formatted duration (MM:SS)', max_length=20, null=True)),
                ('call_meta', models.JSONField(blank=True, default=dict, help_text='Additional call metadata from API')),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='accounts_management_app.ghlconversation')),
            ],
            options={
                'db_table': 'call_record',
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['conversation', 'date_added'], name='call_record_convers_8a27f8_idx'), models.Index(fields=['duration', 'date_added'], name='call_record_duratio_154968_idx'), models.Index(fields=['status', 'date_added'], name='call_record_status_f01a3a_idx'), models.Index(fields=['direction', 'date_added'], name='call_record_directi_11f29b_idx')],
            },
        ),
    ]
