# Generated by Django 5.2.3 on 2025-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0007_callrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='duration',
            field=models.IntegerField(blank=True, default=0, help_text='Call duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
