# Generated by Django 5.2.3 on 2025-07-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0008_alter_callrecord_duration_alter_callrecord_status'),
        ('core', '0017_callreport_ghl_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLWalletBalance',
            fields=[
                ('ghl_credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet_balance', serialize=False, to='core.ghlauthcredentials')),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GHL Wallet Balance',
                'verbose_name_plural': 'GHL Wallet Balances',
            },
        ),
    ]
