# Generated by Django 5.2.3 on 2025-09-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0009_ghlwalletbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='content_type',
            field=models.TextField(default='text/plain'),
        ),
    ]
