# Generated by Django 5.2.3 on 2025-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0010_alter_textmessage_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
