# Generated by Django 5.2.3 on 2025-09-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0013_alter_contact_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='textmessage',
            index=models.Index(fields=['direction', 'date_added'], name='text_messag_directi_666a94_idx'),
        ),
    ]
