# Generated by Django 5.2.3 on 2025-09-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0014_textmessage_text_messag_directi_666a94_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(choices=[('account_view', 'Account View'), ('company_view', 'Company View'), ('bar_graph', 'Bar Graph Analytics'), ('usage_summary', 'Usage Summary')], max_length=20)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], default='all_time', max_length=10)),
                ('data_type', models.CharField(choices=[('sms', 'SMS'), ('call', 'Call'), ('both', 'Both')], default='both', max_length=10)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cached_data', models.JSONField()),
                ('total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'analytics_cache',
                'indexes': [models.Index(fields=['cache_type', 'period_type', 'data_type'], name='analytics_c_cache_t_06ef4e_idx'), models.Index(fields=['start_date', 'end_date'], name='analytics_c_start_d_bccc73_idx'), models.Index(fields=['category_id'], name='analytics_c_categor_730a06_idx'), models.Index(fields=['company_id'], name='analytics_c_company_de8298_idx'), models.Index(fields=['location_id'], name='analytics_c_locatio_0342c3_idx'), models.Index(fields=['is_valid'], name='analytics_c_is_vali_de2b0a_idx'), models.Index(fields=['created_at'], name='analytics_c_created_d13b61_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCacheJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(max_length=20)),
                ('period_type', models.CharField(max_length=10)),
                ('data_type', models.CharField(max_length=10)),
                ('cached_data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_cache_job',
                'indexes': [models.Index(fields=['cache_type', 'status'], name='analytics_c_cache_t_7b75ef_idx'), models.Index(fields=['created_at'], name='analytics_c_created_ad25a8_idx')],
            },
        ),
    ]
