# Generated by Django 5.2.3 on 2025-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0015_analyticscache_analyticscachejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCacheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_cache_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='AnalyticsCacheJob',
        ),
        migrations.RemoveIndex(
            model_name='analyticscache',
            name='analytics_c_cache_t_06ef4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticscache',
            name='analytics_c_start_d_bccc73_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticscache',
            name='analytics_c_categor_730a06_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticscache',
            name='analytics_c_company_de8298_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticscache',
            name='analytics_c_locatio_0342c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='analyticscache',
            name='analytics_c_is_vali_de2b0a_idx',
        ),
        migrations.RenameField(
            model_name='analyticscache',
            old_name='is_valid',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='analyticscache',
            old_name='total_count',
            new_name='record_count',
        ),
        migrations.RemoveField(
            model_name='analyticscache',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='analyticscache',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='analyticscache',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='analyticscache',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='analyticscache',
            name='start_date',
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='company_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='computation_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='date_range_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='date_range_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='location_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='view_type',
            field=models.CharField(blank=True, choices=[('account', 'Account View'), ('company', 'Company View')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analyticscache',
            name='cache_type',
            field=models.CharField(choices=[('usage_analytics_account', 'Usage Analytics - Account View'), ('usage_analytics_company', 'Usage Analytics - Company View'), ('bar_graph_daily', 'Bar Graph - Daily'), ('bar_graph_weekly', 'Bar Graph - Weekly'), ('bar_graph_monthly', 'Bar Graph - Monthly'), ('usage_summary', 'Usage Summary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='analyticscache',
            name='data_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('call', 'Call'), ('both', 'Both SMS and Call')], default='both', max_length=10),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['cache_type', 'view_type', 'data_type'], name='analytics_c_cache_t_f82717_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['is_active'], name='analytics_c_is_acti_e6767b_idx'),
        ),
    ]
