# Generated by Django 5.2.3 on 2025-09-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_management_app', '0016_analyticscachelog_delete_analyticscachejob_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='textmessage',
            name='text_messag_segment_33cbfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='textmessage',
            name='text_messag_directi_666a94_idx',
        ),
        migrations.AddIndex(
            model_name='textmessage',
            index=models.Index(fields=['date_added', 'direction'], name='text_messag_date_ad_2d113c_idx'),
        ),
        migrations.AddIndex(
            model_name='textmessage',
            index=models.Index(fields=['direction'], name='text_messag_directi_971913_idx'),
        ),
        migrations.AddIndex(
            model_name='textmessage',
            index=models.Index(fields=['message_id'], name='text_messag_message_ddfa4b_idx'),
        ),
    ]
